# Pandas

## Оглавление

1. [**Создание DataFrame**](#Создание-DataFrame)
    * 2.1. [Из словаря Python (dictionary)](#Из-словаря-Python-dictionary)
    * 2.2. [Из списка списков Python](#Из-списка-списков-Python)
    * 2.3. [Из массива NumPy (NumPy array)](#Из-массива-NumPy-NumPy-array)
2. [**Операции с DataFrame**](#Операции-с-DataFrame)
    * 3.1. [Просмотр начала и конца DataFrame](#Просмотр-начала-и-конца-DataFrame)
    * 3.2. [Получение общей информации о DataFrame](#Получение-общей-информации-о-DataFrame)
    * 3.3. [Получение описательной статистики](#Получение-описательной-статистики)
    * 3.4. [Выбор столбцов](#Выбор-столбцов)
    * 3.5. [Выбор строк](#Выбор-строк)
        * 3.5.1. [Выбор строк по индексу (`.loc[]` и `.iloc[]`)](#Выбор-строк-по-индексу-loc-и-iloc)
        * 3.5.2. [Выбор нескольких строк по срезу индекса](#Выбор-нескольких-строк-по-срезу-индекса)
    * 3.6. [Фильтрация данных](#Фильтрация-данных)
        * 3.6.1. [Фильтрация по возрасту](#Фильтрация-по-возрасту)
        * 3.6.2. [Фильтрация по городу](#Фильтрация-по-городу)
        * 3.6.3. [Фильтрация по двум условиям (логическое "И")](#Фильтрация-по-двум-условиям-логическое-И)
        * 3.6.4. [Фильтрация по условию "ИЛИ" (возраст < 25 ИЛИ город == 'Петербург')](#Фильтрация-по-условию-ИЛИ-возраст--25-ИЛИ-город--Петербург)
        * 3.6.5. [Фильтрация с отрицанием (НЕ город == 'Казань')](#Фильтрация-с-отрицанием-НЕ-город--Казань)
        * 3.6.6. [Метод `.isin()`](#Метод-isin)
3. [**Добавление нового столбца на основе существующих данных**](#Добавление-нового-столбца-на-основе-существующих-данных)

### Создание DataFrame

1. **Из словаря Python (dictionary):**

   Это один из самых наглядных способов создания DataFrame, особенно если ваши данные уже представлены в виде словаря Python.  Ключи словаря будут использованы в качестве названий столбцов, а значения (списки или массивы NumPy) станут данными для соответствующих столбцов.

   **Важно:**  Все списки или массивы, выступающие в качестве значений словаря, должны иметь одинаковую длину.  Если в качестве значения указан скаляр, он будет автоматически "размножен" (повторен) до необходимой длины, чтобы заполнить весь столбец.

In [7]:
import pandas as pd # Импортируем библиотеку pandas и присваиваем ей псевдоним pd для краткости
import numpy as np

data = {
    'Имя': ['Анна', 'Борис', 'Виктор', 'Григорий'],
    'Возраст': [25, 30, 28, 35],                    
    'Город': ['Москва', 'Петербург', 'Казань', 'Москва']
}

# Создаем DataFrame pandas под названием 'df' из словаря 'data'
df = pd.DataFrame(data)

print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

        Имя  Возраст      Город
0      Анна       25     Москва
1     Борис       30  Петербург
2    Виктор       28     Казань
3  Григорий       35     Москва

2. **Из списка списков Python:**

In [6]:
# Каждый внутренний список представляет собой строку данных для DataFrame.
data_list = [
    ['Елена', 22, 'Самара'],
    ['Иван', 31, 'Владивосток'],
    ['Мария', 27, 'Екатеринбург']
]

# Создаем список 'columns' с названиями столбцов для DataFrame.
# Количество названий столбцов должно соответствовать количеству элементов во внутренних списках 'data_list'.
columns = ['Имя', 'Возраст', 'Город']

# Используем параметр 'columns' для задания названий столбцов.
df_list = pd.DataFrame(data_list, columns=columns)

df_list

     Имя  Возраст         Город
0  Елена       22        Самара
1   Иван       31   Владивосток
2  Мария       27  Екатеринбург

3. **Из массива NumPy:**

In [8]:
numpy_array_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_names = ['Столбец 1', 'Столбец 2', 'Столбец 3']

df_numpy = pd.DataFrame(numpy_array_data, columns=column_names)

df_numpy

   Столбец 1  Столбец 2  Столбец 3
0          1          2          3
1          4          5          6
2          7          8          9

___

### Операции с DataFrame

1. **Просмотр начала и конца DataFrame:**

   Для быстрого ознакомления с содержимым DataFrame и понимания структуры данных, pandas предоставляет удобные методы для просмотра первых и последних строк таблицы.

   * **`.head(n)`: Просмотр первых строк.**  Этот метод отображает первые `n` строк DataFrame. Если значение `n` не указано, по умолчанию отображается 5 первых строк.

   * **`.tail(n)`: Просмотр последних строк.**  Метод `.tail(n)` аналогичен `.head()`, но отображает последние `n` строк DataFrame.  Также, как и в `.head()`, если `n` не указано, отображается 5 последних строк.

In [11]:
print("Первые 5 строк (head()):")
display(df.head()) # По умолчанию первые 5 строк

print("\nПервые 3 строки (head(3)):")
display(df.head(3)) # Первые 3 строки

print("\nПоследние 5 строк (tail()):")
display(df.tail()) # По умолчанию последние 5 строк

print("\nПоследние 2 строки (tail(2)):")
display(df.tail(2)) # Последние 2 строки

Первые 5 строк (head()):

        Имя  Возраст      Город
0      Анна       25     Москва
1     Борис       30  Петербург
2    Виктор       28     Казань
3  Григорий       35     Москва

Первые 3 строки (head(3)):

      Имя  Возраст      Город
0    Анна       25     Москва
1   Борис       30  Петербург
2  Виктор       28     Казань

Последние 5 строк (tail()):

        Имя  Возраст      Город
0      Анна       25     Москва
1     Борис       30  Петербург
2    Виктор       28     Казань
3  Григорий       35     Москва

Последние 2 строки (tail(2)):

        Имя  Возраст   Город
2    Виктор       28  Казань
3  Григорий       35  Москва

2. **Получение общей информации о DataFrame:**

   Метод `.info()` является одним из ключевых инструментов для первичного анализа DataFrame. Он предоставляет сводную информацию о структуре и содержимом таблицы, что помогает быстро оценить общие характеристики данных и выявить потенциальные проблемы.

   * **`.info()`: Вывод сводной информации о DataFrame.** При вызове метода `.info()` для DataFrame, вы получаете следующую важную информацию:

     * **Общая информация о DataFrame:**
         * **Количество строк и столбцов:**  Показывает размерность DataFrame, что позволяет понять объем данных.
     * **Информация о столбцах:**
         * **Названия столбцов (Column names):**  Список всех названий столбцов в DataFrame.
         * **Типы данных столбцов (Data types - dtype):**  Указывает тип данных, хранящихся в каждом столбце (например, `int64`, `float64`, `object`, `datetime64[ns]` и т.д.).
         * **Количество непустых значений (Non-Null Count):**  Для каждого столбца отображается количество не-пустых значений.
     * **Использование памяти (Memory Usage):**
         * **Объем памяти, занимаемый DataFrame:**  Показывает, сколько оперативной памяти использует DataFrame.

In [13]:
print('Информация о DataFrame (info()):\n')
df.info()

Информация о DataFrame (info()):

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Имя      4 non-null      object
 1   Возраст  4 non-null      int64
 2   Город    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

3. **Получение описательной статистики:**

   Метод `.describe()` является мощным инструментом для получения сводной описательной статистики о DataFrame. По умолчанию, `.describe()` применяется к **числовым столбцам** и выводит основные статистические показатели, которые помогают понять распределение и диапазон значений в данных.

   * **`.describe()`: Вывод описательных статистик.** При вызове метода `.describe()` без дополнительных параметров, вы получите следующие статистики для каждого числового столбца:

     * **`count` (Количество):**  Количество непустых (не-NaN) значений в столбце. Показывает, сколько наблюдений есть в данных для данного столбца.
     * **`mean` (Среднее значение):**  Среднее арифметическое значение столбца. Характеризует "центр" распределения данных.
     * **`std` (Стандартное отклонение):**  Стандартное отклонение значений в столбце.  Мера разброса данных относительно среднего значения.
     * **`min` (Минимум):**  Минимальное значение в столбце.
     * **`25%` (25-й процентиль, или первый квартиль):**  Значение, ниже которого находится 25% данных.
     * **`50%` (50-й процентиль, или медиана, второй квартиль):**  Значение, разделяющее данные пополам.  Медиана менее чувствительна к выбросам, чем среднее значение.
     * **`75%` (75-й процентиль, или третий квартиль):**  Значение, ниже которого находится 75% данных.
     * **`max` (Максимум):**  Максимальное значение в столбце.

   **Расширенное использование с `include='all'`:**

   Если вызвать `.describe(include='all')`, метод `.describe()` будет применен ко **всем столбцам DataFrame**, включая нечисловые (например, столбцы с типом данных `object` для строк или `category` для категориальных данных).  Для нечисловых столбцов набор выводимых статистик будет другим и включать, например:

     * **`unique` (Уникальные значения):**  Количество уникальных значений в столбце.
     * **`top` (Самое частое значение):**  Наиболее часто встречающееся значение в столбце.
     * **`freq` (Частота самого частого значения):**  Частота, с которой встречается самое частое значение.

In [15]:
print("\nОписательные статистики (describe()):")
display(df.describe()) # Статистики только для числового столбца 'Возраст'

print("\nОписательные статистики для всех столбцов (describe(include='all')):")
display(df.describe(include='all')) # Статистики для всех столбцов

Описательные статистики (describe()):

         Возраст
count   4.000000
mean   29.500000
std     4.203173
min    25.000000
25%    27.250000
50%    29.000000
75%    31.250000
max    35.000000

Описательные статистики для всех столбцов (describe(include='all')):

         Имя    Возраст   Город
count      4   4.000000       4
unique     4        NaN       3
top     Анна        NaN  Москва
freq       1        NaN       2
mean     NaN  29.500000     NaN
std      NaN   4.203173     NaN
min      NaN  25.000000     NaN
25%      NaN  27.250000     NaN
50%      NaN  29.000000     NaN
75%      NaN  31.250000     NaN
max      NaN  35.000000     NaN

---

### Выбор столбцов и строк

1. **Выбор столбцов:**

   DataFrame предоставляет различные способы для выбора одного или нескольких столбцов.  Самый простой способ выбрать один столбец - это использовать его имя.

   * **Выбор одного столбца по имени:**  Для выбора одного столбца из DataFrame, используйте имя столбца, заключенное в квадратные скобки `[]`, после имени DataFrame.  Этот способ аналогичен доступу к значению в словаре Python по ключу.

     **Результатом операции выбора одного столбца является объект Pandas Series.**  Pandas Series представляет собой одномерный помеченный массив данных.  По сути, это столбец из DataFrame.

In [17]:
column_name = df['Имя'] # Выбираем столбец 'Имя'
column_age = df['Возраст'] # Выбираем столбец 'Возраст'

print("Столбец 'Имя':")
display(column_name)
print(type(column_name)) # Проверяем тип - это Pandas Series

print("\nСтолбец 'Возраст':")
display(column_age)

Столбец 'Имя':

0        Анна
1       Борис
2      Виктор
3    Григорий
Name: Имя, dtype: object

<class 'pandas.core.series.Series'>

Столбец 'Возраст':

0    25
1    30
2    28
3    35
Name: Возраст, dtype: int64

2. **Выбор нескольких столбцов:**

   Для выбора **нескольких** столбцов из DataFrame одновременно, потребуется передать **список** с именами нужных столбцов в квадратных скобках `[]` после имени DataFrame.

   **Результатом этой операции будет создан новый DataFrame**, который будет содержать только те столбцы, имена которых были указаны в списке.  Исходный DataFrame при этом остается неизменным.

In [18]:
selected_columns_df = df[['Имя', 'Город']]

print("\nDataFrame с выбранными столбцами ('Имя', 'Город'):")
display(selected_columns_df)
print(type(selected_columns_df)) # Проверяем тип - это DataFrame

DataFrame с выбранными столбцами ('Имя', 'Город'):

        Имя      Город
0      Анна     Москва
1     Борис  Петербург
2    Виктор     Казань
3  Григорий     Москва

<class 'pandas.core.frame.DataFrame'>

3. **Выбор строк:**

   Выбор строк в DataFrame отличается от выбора столбцов и осуществляется преимущественно с использованием **индексации**.  Основными методами для выбора строк являются индексация по **индексу** (метке строки) или **логическая индексация** (фильтрация строк на основе условий).

   * **Выбор строк по индексу (`.loc[]` и `.iloc[]`):**

     Pandas предоставляет два основных метода для выбора строк по индексу, отличающихся способом указания индекса:

     * **`.loc[]` (индексация по метке, label-based indexing):**  Метод `.loc[]` используется для выбора строк на основе **метки индекса** (label).  Метка индекса - это значение, которое идентифицирует каждую строку DataFrame.  По умолчанию, метками индекса являются целые числа, начинающиеся с 0, но индекс DataFrame может быть изменен на другие значения (например, строки, даты и т.д.).  При использовании `.loc[]` вы обращаетесь к строкам, используя именно эти метки.

     * **`.iloc[]` (индексация по целочисленной позиции, integer-location based indexing):** Метод `.iloc[]` используется для выбора строк на основе их **целочисленной позиции** (integer location).  В отличие от `.loc[]`, `.iloc[]` всегда использует **порядковый номер строки**, начиная с 0 для первой строки, 1 для второй и так далее, независимо от фактических меток индекса.  `.iloc[]` работает аналогично индексации в списках и массивах Python по числовому индексу.

In [21]:
row_index_2_loc = df.loc[2] # Выбираем строку с индексом 2
row_index_1_iloc = df.iloc[1] # Выбираем строку на позиции 1

display(df)

print("\nСтрока с индексом 2 (loc[2]):")
display(row_index_2_loc)
print(type(row_index_2_loc)) # Pandas Series (строка DataFrame - это тоже Series)

print("\nСтрока на позиции 1 (iloc[1]):")
display(row_index_1_iloc)

        Имя  Возраст      Город
0      Анна       25     Москва
1     Борис       30  Петербург
2    Виктор       28     Казань
3  Григорий       35     Москва

Строка с индексом 2 (loc[2]):

Имя        Виктор
Возраст        28
Город      Казань
Name: 2, dtype: object

<class 'pandas.core.series.Series'>

Строка на позиции 1 (iloc[1]):

Имя            Борис
Возраст           30
Город      Петербург
Name: 1, dtype: object

4. **Выбор нескольких строк по срезу индекса:**

   Для выбора диапазона строк (среза строк) из DataFrame, вы можете использовать **срезы индексов** с методами `.loc[]` и `.iloc[]`.  Срезы позволяют выбрать последовательность строк, основываясь на их метках индекса (для `.loc[]`) или целочисленных позициях (для `.iloc[]`).

   * **Срезы с `.loc[]` (label-based slicing):**  При использовании `.loc[]` для срезов, вы указываете **метки начального и конечного индекса среза**.  Важно отметить, что при использовании `.loc[]` **конечная метка индекса включается в срез**.  Срез с `.loc[]` вернет все строки, метки индекса которых находятся в диапазоне от начальной до конечной (включительно).

   * **Срезы с `.iloc[]` (integer-location based slicing):**  При использовании `.iloc[]` для срезов, вы указываете **целочисленные позиции начального и конечного индекса среза**.  В отличие от `.loc[]`, при использовании `.iloc[]` **конечная позиция индекса не включается в срез**.  Срез с `.iloc[]` вернет строки, чьи целочисленные позиции находятся в диапазоне от начальной до конечной (не включая конечную).  Это поведение аналогично стандартным срезам в Python для списков и строк.

In [22]:
rows_indices_1_to_3_loc = df.loc[1:3] # Срез строк с индексами от 1 до 3 (включительно! для .loc!)
rows_positions_0_to_2_iloc = df.iloc[0:3] # Срез строк с позициями от 0 до 2 (не включая 3! для .iloc!)

print("\nСтроки с индексами 1:3 (loc[1:3]):")
display(rows_indices_1_to_3_loc) # Обрати внимание, что строка с индексом 3 ВКЛЮЧЕНА

print("\nСтроки с позициями 0:2 (iloc[0:3]):")
display(rows_positions_0_to_2_iloc) # Обрати внимание, что строка на позиции 3 НЕ ВКЛЮЧЕНА

Строки с индексами 1:3 (loc[1:3]):

        Имя  Возраст      Город
1     Борис       30  Петербург
2    Виктор       28     Казань
3  Григорий       35     Москва

Строки с позициями 0:2 (iloc[0:3]):

      Имя  Возраст      Город
0    Анна       25     Москва
1   Борис       30  Петербург
2  Виктор       28     Казань

___

### Фильтрация данных

Основным и мощным механизмом фильтрации данных в Pandas является **логическая индексация** (или **булева индексация**, boolean indexing).  Этот метод позволяет отбирать строки DataFrame, соответствующие определенным условиям, на основе создания так называемой "булевой маски".

**Принцип работы логической индексации:**

1. **Создание "булевой маски" (boolean mask):**
   На первом шаге формируется **булева маска** – объект Pandas Series (или NumPy массив) той же длины, что и количество строк в DataFrame.  Каждый элемент этой Series представляет собой булево значение: `True` или `False`. Значение `True` в маске указывает на то, что соответствующая строка в DataFrame удовлетворяет заданному условию, а `False` – не удовлетворяет.

2. **Использование булевой маски для индексации DataFrame:**
   На втором шаге, созданная булева маска используется для индексации DataFrame.  Маска передается в квадратных скобках `[]` после имени DataFrame. В результате Pandas возвращает **новый DataFrame**, содержащий только те строки, для которых в булевой маске установлено значение `True`.  Строки, которым соответствуют значения `False` в маске, исключаются из результирующего DataFrame.

**Как создать булеву маску?**

Булевы маски, как правило, создаются путем применения **операторов сравнения** и **логических операторов** к столбцам DataFrame.  Результатом таких операций является Pandas Series булевых значений, которая и служит булевой маской.

**Операторы сравнения (comparison operators):**

* `>`  (больше)
* `<`  (меньше)
* `>=` (больше или равно)
* `<=` (меньше или равно)
* `==` (равно)
* `!=` (не равно)

**Логические операторы (logical operators):**

* `&`  (логическое "И" - **AND**) - для объединения нескольких условий, которые должны выполняться **одновременно**.
* `|`  (логическое "ИЛИ" - **OR**)  - для объединения нескольких условий, когда достаточно выполнения **хотя бы одного** из них.
* `~`  (логическое "НЕ" - **NOT**, инверсия) - для **инвертирования** булевой маски, то есть замены `True` на `False` и наоборот.

In [23]:
df = pd.DataFrame(data)

1. **Фильтрация по возрасту:**

   Рассмотрим пример фильтрации DataFrame по значениям столбца 'Возраст'.  Наша задача - отобрать из DataFrame только те строки, в которых значение в столбце 'Возраст' превышает 30 лет.  Для этого мы создадим булеву маску, основанную на условии `df['Возраст'] > 30`, и применим ее для фильтрации DataFrame.

In [27]:
age_filter = df['Возраст'] > 30 # Создаем булеву маску: True для строк, где 'Возраст' > 30, False - иначе
filtered_df_age = df[age_filter] # Применяем маску к DataFrame, получаем отфильтрованный DataFrame

print("Отфильтрованный DataFrame (возраст > 30):\n")
display(filtered_df_age)
print(type(age_filter)) # Проверяем тип age_filter - это Pandas Series (булева маска)

Отфильтрованный DataFrame (возраст > 30):

        Имя  Возраст   Город
3  Григорий       35  Москва

<class 'pandas.core.series.Series'>

2. **Фильтрация по городу:**

   Рассмотрим другой пример фильтрации, на этот раз по текстовому столбцу 'Город'.  Предположим, мы хотим выбрать из DataFrame только строки, соответствующие жителям Москвы.  Для этого мы создадим булеву маску, проверяющую равенство значения в столбце 'Город' строке 'Москва', и применим эту маску для фильтрации.

In [28]:
city_filter = df['Город'] == 'Москва' # Булева маска: True для 'Город' == 'Москва'
filtered_df_city = df[city_filter] # Фильтруем DataFrame

print("Отфильтрованный DataFrame (город == 'Москва'):\n")
display(filtered_df_city)

Отфильтрованный DataFrame (город == 'Москва'):

        Имя  Возраст   Город
0      Анна       25  Москва
3  Григорий       35  Москва

3. **Фильтрация по двум условиям (логическое "И"):**

   В более сложных сценариях анализа данных часто возникает необходимость фильтровать DataFrame по **нескольким условиям одновременно**.  Например, мы можем захотеть отобрать строки, которые удовлетворяют **и одному, и другому условию**.  Для объединения нескольких условий фильтрации в Pandas используется **логический оператор "И" (`&`)**.

   **Важно!** При использовании логических операторов (`&`, `|`, `~`) для объединения условий фильтрации, **каждое отдельное условие необходимо заключать в круглые скобки `()`**.  Это связано с приоритетом операций в Python и необходимо для корректной работы логической индексации.

In [29]:
complex_filter = (df['Возраст'] > 30) & (df['Город'] == 'Москва') # Комбинируем два условия с помощью &
filtered_df_complex = df[complex_filter] # Фильтруем DataFrame

print("Отфильтрованный DataFrame (возраст > 30 И город == 'Москва'):\n")
display(filtered_df_complex)

Отфильтрованный DataFrame (возраст > 30 И город == 'Москва'):

        Имя  Возраст   Город
3  Григорий       35  Москва

4. **Фильтрация по условию "ИЛИ" (возраст < 25 ИЛИ город == 'Петербург'):**

   В дополнение к логическому "И", для фильтрации данных часто требуется использовать **логическое "ИЛИ" (`|`)**.  Оператор "ИЛИ" позволяет отобрать строки DataFrame, которые удовлетворяют **хотя бы одному из нескольких заданных условий**.  В данном примере мы рассмотрим фильтрацию строк, где значение столбца 'Возраст' **меньше 25 лет ИЛИ** значение столбца 'Город' равно 'Петербург'.

   Как и в случае с оператором "И", при использовании логического "ИЛИ" (`|`), **каждое отдельное условие также необходимо заключать в круглые скобки `()`** для обеспечения корректной интерпретации и выполнения фильтрации.

In [30]:
complex_filter_or = (df['Возраст'] < 25) | (df['Город'] == 'Петербург') # Комбинируем условия с помощью |
filtered_df_complex_or = df[complex_filter_or] # Фильтруем DataFrame

print("\nОтфильтрованный DataFrame (возраст < 25 ИЛИ город == 'Петербург'):\n")
display(filtered_df_complex_or)

Отфильтрованный DataFrame (возраст < 25 ИЛИ город == 'Петербург'):

     Имя  Возраст      Город
1  Борис       30  Петербург

5. **Фильтрация с отрицанием (НЕ город == 'Казань'):**

   В Pandas также доступна операция **отрицания**, которая позволяет инвертировать логическое условие.  Для реализации отрицания в логической индексации используется **логический оператор "НЕ" (`~`)**.  Этот оператор позволяет выбрать строки DataFrame, **НЕ** соответствующие заданному условию.  В данном примере мы отфильтруем DataFrame, исключив из него все строки, где значение столбца 'Город' равно 'Казань'.

   Оператор отрицания `~` применяется **перед** условием, которое нужно инвертировать.  Как и в случаях с операторами "И" и "ИЛИ", если условие, к которому применяется отрицание, является сложным (состоит из нескольких частей), его **также рекомендуется заключать в круглые скобки `()`** для явного указания приоритета операций и избежания ошибок.

In [31]:
not_kazan_filter = ~(df['Город'] == 'Казань') # Инвертируем условие "город == 'Казань'"
filtered_df_not_kazan = df[not_kazan_filter] # Фильтруем DataFrame

print("\nОтфильтрованный DataFrame (НЕ город == 'Казань'):\n")
display(filtered_df_not_kazan)

Отфильтрованный DataFrame (НЕ город == 'Казань'):

        Имя  Возраст      Город
0      Анна       25     Москва
1     Борис       30  Петербург
3  Григорий       35     Москва

Метод `.isin()`

Метод `.isin(values)` в Pandas является удобным и эффективным инструментом для фильтрации данных по **принадлежности к набору значений**.  Этот метод применяется к объекту Pandas Series (то есть, к столбцу DataFrame) и принимает в качестве аргумента список (или любой другой итерируемый объект, например, кортеж или множество) значений.

**Принцип работы `.isin()`:**

Метод `.isin(values)` проверяет **для каждого элемента** в Series, содержится ли это значение в переданном списке `values`.  В результате, он возвращает **булеву Series** той же длины, что и исходная Series.  В возвращенной Series значение `True` будет стоять на тех позициях, где значение в исходной Series **найдено в списке `values`**, и `False` – в противном случае.

**Преимущества использования `.isin()` для фильтрации:**

Метод `.isin()` особенно полезен, когда необходимо выполнить фильтрацию по **нескольким значениям одновременно**, что часто встречается на практике.  Использование `.isin()` делает код более **читабельным, лаконичным и эффективным**, по сравнению с использованием множественных условий, объединенных логическим оператором "ИЛИ" (`|`).

**Пример использования `.isin()` для фильтрации по городу:**

Ранее мы рассматривали фильтрацию по условию "город == 'Петербург' ИЛИ город == 'Казань'".  Тот же результат можно достичь, используя метод `.isin()` гораздо более элегантным и понятным способом.

Вместо использования логического оператора "ИЛИ":

```python
city_piter_or_kazan_filter = (df['Город'] == 'Петербург') | (df['Город'] == 'Казань')

___

### Добавление новых столбцов

1. Добавление нового столбца на основе существующих данных:

In [20]:
print('Исхродный DataFrame:\n', df)

df['Приветствие'] = 'Привет, ' + df['Имя'] + ' ! Добро пожаловать в ' + df['Город'] + '!'

print('\nDataFrame с новым столбцом "Приветствие":\n', df)

Исхродный DataFrame:
         Имя  Возраст        Город
0      Анна       25       Москва
1     Борис       30    Петербург
2    Виктор       28       Казань
3  Григорий       35       Москва
4     Дарья       22  Владивосток
5   Евгений       40       Москва
6     Жанна       29    Петербург
7     Злата       33       Казань

DataFrame с новым столбцом "Приветствие":
         Имя  Возраст        Город  \
0      Анна       25       Москва
1     Борис       30    Петербург
2    Виктор       28       Казань
3  Григорий       35       Москва
4     Дарья       22  Владивосток
5   Евгений       40       Москва
6     Жанна       29    Петербург
7     Злата       33       Казань

                                       Приветствие
0        Привет, Анна ! Добро пожаловать в Москва!
1    Привет, Борис ! Добро пожаловать в Петербург!
2      Привет, Виктор ! Добро пожаловать в Казань!
3    Привет, Григорий ! Добро пожаловать в Москва!
4  Привет, Дарья ! Добро пожаловать в Владивосток!
5     Привет, Евгений ! Добро пожаловать в Москва!
6    Привет, Жанна ! Добро пожаловать в Петербург!
7       Привет, Злата ! Добро пожаловать в Казань!

df['Приветствие'] = ... – Так мы создаем новый столбец с именем 'Приветствие' в DataFrame df. Если столбца с таким именем еще нет, он будет создан. Если уже есть – его значения будут перезаписаны.

'Привет, ' + df['Имя'] + '! Добро пожаловать в ' + df['Город'] + '!' – Выражение справа от знака = определяет значения для нового столбца. Здесь мы используем векторизованные операции Pandas:

df['Имя'] и df['Город'] – это Pandas Series (столбцы DataFrame).

'Привет, ', '! Добро пожаловать в ', '!' – это строковые константы.

Оператор + в Pandas в данном случае работает как векторизованное строковое сложение. Он поэлементно объединяет строки из Series df['Имя'], df['Город'] и строковые константы, создавая новые строки для столбца 'Приветствие'.

Задание:

2. Добаваление столбца с константным значением:

In [21]:
df['Страна'] = 'Россия'
print('Dataframe с новым столбцом "Страна"', df)

Dataframe с новым столбцом "Страна"         Имя  Возраст        Город  \
0      Анна       25       Москва
1     Борис       30    Петербург
2    Виктор       28       Казань
3  Григорий       35       Москва
4     Дарья       22  Владивосток
5   Евгений       40       Москва
6     Жанна       29    Петербург
7     Злата       33       Казань

                                       Приветствие  Страна
0        Привет, Анна ! Добро пожаловать в Москва!  Россия
1    Привет, Борис ! Добро пожаловать в Петербург!  Россия
2      Привет, Виктор ! Добро пожаловать в Казань!  Россия
3    Привет, Григорий ! Добро пожаловать в Москва!  Россия
4  Привет, Дарья ! Добро пожаловать в Владивосток!  Россия
5     Привет, Евгений ! Добро пожаловать в Москва!  Россия
6    Привет, Жанна ! Добро пожаловать в Петербург!  Россия
7       Привет, Злата ! Добро пожаловать в Казань!  Россия

3. Использование .assign() для добавления столбцов:

In [22]:
df_assigned = df.assign(
    Пол = ['Жен', 'Муж', 'Муж', 'Муж', 'Жен', 'Муж', 'Муж', 'Муж']
)

print("\nDataFrame, созданный с помощью .assign() с новым столбцом 'Пол':\n", df_assigned)
print("\nИсходный DataFrame (df) - не изменился:\n", df) # Исходный DataFrame df остался без изменений

DataFrame, созданный с помощью .assign() с новым столбцом 'Пол':
         Имя  Возраст        Город  \
0      Анна       25       Москва
1     Борис       30    Петербург
2    Виктор       28       Казань
3  Григорий       35       Москва
4     Дарья       22  Владивосток
5   Евгений       40       Москва
6     Жанна       29    Петербург
7     Злата       33       Казань

                                       Приветствие  Страна  Пол
0        Привет, Анна ! Добро пожаловать в Москва!  Россия  Жен
1    Привет, Борис ! Добро пожаловать в Петербург!  Россия  Муж
2      Привет, Виктор ! Добро пожаловать в Казань!  Россия  Муж
3    Привет, Григорий ! Добро пожаловать в Москва!  Россия  Муж
4  Привет, Дарья ! Добро пожаловать в Владивосток!  Россия  Жен
5     Привет, Евгений ! Добро пожаловать в Москва!  Россия  Муж
6    Привет, Жанна ! Добро пожаловать в Петербург!  Россия  Муж
7       Привет, Злата ! Добро пожаловать в Казань!  Россия  Муж

Исходный DataFrame (df) - не изменился:
         Имя  Возраст        Город  \
0      Анна       25       Москва
1     Борис       30    Петербург
2    Виктор       28       Казань
3  Григорий       35       Москва
4     Дарья       22  Владивосток
5   Евгений       40       Москва
6     Жанна       29    Петербург
7     Злата       33       Казань

                                       Приветствие  Страна
0        Привет, Анна ! Добро пожаловать в Москва!  Россия
1    Привет, Борис ! Добро пожаловать в Петербург!  Россия
2      Привет, Виктор ! Добро пожаловать в Казань!  Россия
3    Привет, Григорий ! Добро пожаловать в Москва!  Россия
4  Привет, Дарья ! Добро пожаловать в Владивосток!  Россия
5     Привет, Евгений ! Добро пожаловать в Москва!  Россия
6    Привет, Жанна ! Добро пожаловать в Петербург!  Россия
7       Привет, Злата ! Добро пожаловать в Казань!  Россия

In [23]:
new_df = pd.DataFrame(data)
print(new_df, '\n')
new_df['Возраст_через_5_лет'] = new_df['Возраст'] + 5
new_df['Активный'] = True
new_df_assign = new_df.assign(
    Возраст_в_квадрате = df['Возраст'] ** 2,
    Категория = 'Не определено'
)

print(new_df)
print('\n--------------\n')
print(new_df_assign.head())

        Имя  Возраст        Город
0      Анна       25       Москва
1     Борис       30    Петербург
2    Виктор       28       Казань
3  Григорий       35       Москва
4     Дарья       22  Владивосток
5   Евгений       40       Москва
6     Жанна       29    Петербург
7     Злата       33       Казань

        Имя  Возраст        Город  Возраст_через_5_лет  Активный
0      Анна       25       Москва                   30      True
1     Борис       30    Петербург                   35      True
2    Виктор       28       Казань                   33      True
3  Григорий       35       Москва                   40      True
4     Дарья       22  Владивосток                   27      True
5   Евгений       40       Москва                   45      True
6     Жанна       29    Петербург                   34      True
7     Злата       33       Казань                   38      True

--------------

        Имя  Возраст        Город  Возраст_через_5_лет  Активный  \
0      Анна       25       Москва                   30      True
1     Борис       30    Петербург                   35      True
2    Виктор       28       Казань                   33      True
3  Григорий       35       Москва                   40      True
4     Дарья       22  Владивосток                   27      True

   Возраст_в_квадрате      Категория
0                 625  Не определено
1                 900  Не определено
2                 784  Не определено
3                1225  Не определено
4                 484  Не определено

### Изменение значений в столбцах DataFrame

1. Изменение значений поэлементально

Самый простой способ изменить значения в столбце – это присвоить столбцу новые значения. Это похоже на то, как мы создавали новые столбцы, но теперь мы будем использовать имя существующего столбца в левой части присваивания.

In [24]:
data = {
    'Имя': ['Анна', 'Борис', 'Виктор', 'Григорий'],
    'Возраст': [25, 30, 28, 35],
    'Город': ['Москва', 'Петербург', 'Казань', 'Москва']
}
df = pd.DataFrame(data)
print("Исходный DataFrame:\n", df)

Исходный DataFrame:
         Имя  Возраст      Город
0      Анна       25     Москва
1     Борис       30  Петербург
2    Виктор       28     Казань
3  Григорий       35     Москва

Допустим, мы хотим увеличить возраст всех людей на 1 год. Мы можем сделать это так:

In [25]:
df['Возраст'] = df['Возраст'] + 1

print("\nDataFrame с измененным столбцом 'Возраст':\n", df)

DataFrame с измененным столбцом 'Возраст':
         Имя  Возраст      Город
0      Анна       26     Москва
1     Борис       31  Петербург
2    Виктор       29     Казань
3  Григорий       36     Москва

2. Изменение значений на основе условий:

Часто нужно изменять значения в столбце только для определенных строк, которые удовлетворяют какому-то условию. Например, мы хотим сделать возраст 0 для всех людей, у которых возраст меньше 25.

In [26]:
condition = df['Возраст'] < 30 # Создаём булеву маску, где возраст < 30

df.loc[condition, 'Возраст'] = 0 # Изменяем 'Возраст' на 0 только для строк, где condition == True

print("\nDataFrame с измененным 'Возраст' (для возраста < 30 установлено 0):\n", df)

DataFrame с измененным 'Возраст' (для возраста < 30 установлено 0):
         Имя  Возраст      Город
0      Анна        0     Москва
1     Борис       31  Петербург
2    Виктор        0     Казань
3  Григорий       36     Москва

Пояснение:

condition = df['Возраст'] < 25 – Создаем булеву маску condition, которая True для строк, где возраст меньше 25, и False в противном случае.

df.loc[condition, 'Возраст'] = 0 – Вот здесь происходит условное изменение значений:

df.loc[...] – Используем .loc[] для выбора строк и столбцов.

condition – Первый аргумент в .loc[] – это булева маска condition. Она выбирает строки, для которых нужно выполнить изменение.

'Возраст' – Второй аргумент в .loc[] – это имя столбца 'Возраст'. Он выбирает столбец, в котором нужно произвести изменение.

= 0 – Присваиваем значение 0 выбранным ячейкам (строкам, удовлетворяющим условию, и столбцу 'Возраст').

3. Переименование столбцов:
Иногда нужно переименовать столбцы DataFrame, чтобы сделать их имена более понятными, удобными для работы или соответствующими каким-то стандартам. Для этого используется метод .rename().
.rename(columns=mapping): Переименовывает столбцы. Аргумент columns принимает словарь, где ключи - это старые имена столбцов, а значения - новые имена.

In [28]:
df_renamed = df.rename(columns={'Возраст': 'Лет', 'Город': 'Населённый пункт'}) # переименовывам столбцы

print("\nDataFrame с переименованными столбцами:\n", df_renamed)
print("\nИсходный DataFrame (df) - не изменился:\n", df) # Исходный DataFrame df остался с прежними именами столбцов

DataFrame с переименованными столбцами:
         Имя  Лет Населённый пункт
0      Анна    0           Москва
1     Борис   31        Петербург
2    Виктор    0           Казань
3  Григорий   36           Москва

Исходный DataFrame (df) - не изменился:
         Имя  Возраст      Город
0      Анна        0     Москва
1     Борис       31  Петербург
2    Виктор        0     Казань
3  Григорий       36     Москва

Важно: .rename() тоже не изменяет исходный DataFrame, а возвращает новый. Если ты хочешь изменить DataFrame "на месте", используй параметр inplace=True: df.rename(columns={'Возраст': 'Лет'}, inplace=True). Но в большинстве случаев рекомендуется использовать функциональный стиль и работать с новыми DataFrame, чтобы случайно не изменить исходные данные.

### Применение функций к DataFrame

Зачем применять функции к столбцам?

Представь себе ситуации, когда тебе нужно:

Очистить данные: Например, удалить лишние пробелы в строках, привести все строки к нижнему регистру, заменить какие-то символы.

Преобразовать данные: Например, перевести даты из одного формата в другой, извлечь год или месяц из даты, преобразовать числовые значения в другие единицы измерения.

Создать новые признаки (feature engineering): Например, на основе столбца с полным именем создать столбцы 'Имя' и 'Фамилия', рассчитать длину строк, определить категорию на основе числового значения.

Выполнить сложные вычисления: Применить какую-то сложную математическую формулу к каждому значению в столбце, использовать внешнюю функцию или библиотеку для обработки данных в столбце.

Во всех этих случаях применение функций к столбцам DataFrame – это незаменимый инструмент. Pandas предоставляет для этого очень гибкий и удобный метод .apply().

Метод .apply()

Метод .apply() можно применять как к Series (столбцу DataFrame), так и к DataFrame целиком.

Применение к Series (Series.apply(func)): Применяет функцию func к каждому значению в Series. Возвращает Series, где каждый элемент - это результат применения функции к соответствующему элементу исходной Series.

Применение к DataFrame (DataFrame.apply(func, axis=0 или axis=1)): Применяет функцию func к столбцам (axis=0) или строкам (axis=1) DataFrame.

Если axis=0 (по умолчанию) – функция применяется к каждому столбцу. В функцию передается Series, представляющий столбец. Возвращает Series, где индексы - это имена столбцов, а значения - результаты применения функции к каждому столбцу.

Если axis=1 – функция применяется к каждой строке. В функцию передается Series, представляющий строку. Возвращает Series, где индексы - это индексы строк, а значения - результаты применения функции к каждой строке.

1. Применение к столбцу

In [29]:
data = {
    'ФИО': ['Анна Иванова', 'Борис Петров', 'Виктор Смирнов', 'Григорий Соколов'],
    'Возраст_в_годах': [26, 31, 29, 36],
    'Населенный пункт': ['Москва', 'Петербург', 'Казань', 'Москва']
}
df = pd.DataFrame(data)

Допустим, мы хотим посчитать длину строки в столбце 'ФИО' для каждого человека. Мы можем использовать функцию len() и метод .apply():

In [30]:
def get_name_length(fio):
    return len(fio)

name_length_series = df['ФИО'].apply(get_name_length)

print("\nSeries с длиной ФИО:\n", name_length_series)
print(type(name_length_series)) # Результат - Pandas Series

Series с длиной ФИО:
 0    12
1    12
2    14
3    16
Name: ФИО, dtype: int64
<class 'pandas.core.series.Series'>

2. Использование lambda-функций для краткости:

Вместо того, чтобы определять функцию get_name_length() отдельно, мы можем использовать lambda-функцию прямо внутри .apply(). Lambda-функции - это короткие анонимные функции, которые удобно использовать "на лету".

In [31]:
name_length_series_lambda = df['ФИО'].apply(lambda fio: len(fio))

print("\nSeries с длиной ФИО (с lambda-функцией):\n", name_length_series_lambda) # Результат тот же

Series с длиной ФИО (с lambda-функцией):
 0    12
1    12
2    14
3    16
Name: ФИО, dtype: int64

3. Применение к DataFrame (к столбцам, axis=0):

Допустим, мы хотим найти максимальный возраст в каждом столбце (хотя в нашем DataFrame только один числовой столбец 'Возраст_в_годах', но для примера представим, что их несколько). Мы можем использовать метод .apply() к DataFrame с axis=0:

In [33]:
max_age_per_column_series = df.apply(max, axis=0) # Применяем функцию max к каждому столбцу (axis=0)

print("\nSeries с максимальным возрастом по столбцам:\n", max_age_per_column_series) # Результат - Series с максимальными значениями по столбцам

Series с максимальным возрастом по столбцам:
 ФИО                 Григорий Соколов
Возраст_в_годах                   36
Населенный пункт           Петербург
dtype: object

4. Применение к DataFrame (к строкам, axis=1):  
Допустим, мы хотим создать новый столбец 'Информация', который будет содержать строку с информацией о каждом человеке, включая ФИО и возраст. Нам нужно применить функцию к каждой строке DataFrame, поэтому используем .apply(..., axis=1):

In [34]:
def create_info_string(row):
    return f'ФИО: {row['ФИО']}, Возраст: {row['Возраст_в_годах']}'

info_column_series = df.apply(create_info_string, axis=1) # Применяем функцию create_info_string к каждой строке (axis=1)
df['Информация'] = info_column_series # Добавляем полученную Series как новый столбец 'Информация' в DataFrame

print("\nDataFrame с новым столбцом 'Информация':\n", df)

DataFrame с новым столбцом 'Информация':
                 ФИО  Возраст_в_годах Населенный пункт  \
0      Анна Иванова               26           Москва
1      Борис Петров               31        Петербург
2    Виктор Смирнов               29           Казань
3  Григорий Соколов               36           Москва

                           Информация
0      ФИО: Анна Иванова, Возраст: 26
1      ФИО: Борис Петров, Возраст: 31
2    ФИО: Виктор Смирнов, Возраст: 29
3  ФИО: Григорий Соколов, Возраст: 36

Пояснение:

def create_info_string(row): ... – Определяем функцию create_info_string, которая принимает на вход row - Pandas Series, представляющую строку DataFrame. Внутри функции мы можем обращаться к элементам строки по именам столбцов (например, row['ФИО'], row['Возраст_в_годах']). Функция возвращает строку с информацией.

df.apply(create_info_string, axis=1) – Применяем функцию create_info_string к DataFrame df по строкам (axis=1). Для каждой строки в функцию create_info_string будет передана Series, представляющая эту строку. Результатом .apply(..., axis=1) будет Series, где каждый элемент - это результат применения функции к соответствующей строке.

df['Информация'] = info_column_series – Добавляем полученную Series info_column_series как новый столбец 'Информация' в DataFrame df.

Важно: Метод .apply() - очень гибкий, но не всегда самый быстрый. В Pandas и NumPy многие операции можно выполнить векторизованно, то есть без явного применения функций к каждой строке или элементу. Векторизованные операции обычно работают гораздо быстрее, чем .apply(). Поэтому, если есть возможность выполнить операцию векторизованно, лучше использовать векторизацию. Но .apply() незаменим, когда нужна сложная логика или применение внешних функций, которые не имеют векторизованной реализации в Pandas.

### Сортировка DataFrame

Сортировка DataFrame – это процесс упорядочивания строк DataFrame по значениям одного или нескольких столбцов, или по индексу. Сортировка очень полезна, когда ты хочешь:

Упорядочить данные для лучшего восприятия: Например, отсортировать список клиентов по имени или дате регистрации.

Найти минимальные или максимальные значения: Отсортировав DataFrame по определенному столбцу, ты легко сможешь найти строки с наименьшими или наибольшими значениями в этом столбце.

Подготовить данные для анализа или визуализации: Некоторые виды анализа и визуализации требуют, чтобы данные были отсортированы в определенном порядке.

Основные методы сортировки в Pandas:

.sort_values(by, axis=0, ascending=True, inplace=False, ...): Сортировка DataFrame по значениям одного или нескольких столбцов.

by – Имя столбца (строка) или список имен столбцов, по которым нужно сортировать. Если список - сортировка будет лексикографической (сначала по первому столбцу, потом по второму при равенстве первых, и т.д.).

axis=0 – Сортировать строки (по умолчанию). axis=1 - для сортировки столбцов (редко используется).

ascending=True – Сортировать по возрастанию (по умолчанию). ascending=False – для сортировки по убыванию.

inplace=False – Вернуть новый отсортированный DataFrame (по умолчанию). inplace=True – изменить исходный DataFrame "на месте" (без возвращения нового DataFrame). Рекомендуется избегать inplace=True и работать с новыми DataFrame, чтобы не изменять исходные данные случайно.

na_position='last' (по умолчанию) – Пропущенные значения (NaN) помещаются в конец отсортированного DataFrame. na_position='first' – для помещения NaN в начало.

.sort_index(axis=0, ascending=True, inplace=False, ...): Сортировка DataFrame по индексу.

Параметры axis, ascending, inplace, na_position работают аналогично .sort_values(), но здесь сортировка происходит по значениям индекса, а не столбцов.

In [ ]:
data = {
    'ФИО': ['Анна Иванова', 'Борис Петров', 'Виктор Смирнов', 'Григорий Соколов', 'Дарья Морозова'],
    'Возраст_в_годах': [26, 31, 29, 36, 24],
    'Населенный пункт': ['Москва', 'Петербург', 'Казань', 'Москва', 'Петербург']
}
df = pd.DataFrame(data)

1. Сортировка по одному столбцу:

In [35]:
df_sorted_by_fio = df.sort_values(by='ФИО') # Сортируем по столбцу 'ФИО' (по умолчанию ascending=True)

print("\nDataFrame, отсортированный по 'ФИО' (по возрастанию):\n", df_sorted_by_fio)
print("\nИсходный DataFrame (df) - не изменился:\n", df) # Исходный DataFrame df остался в исходном порядке

DataFrame, отсортированный по 'ФИО' (по возрастанию):
                 ФИО  Возраст_в_годах Населенный пункт  \
0      Анна Иванова               26           Москва
1      Борис Петров               31        Петербург
2    Виктор Смирнов               29           Казань
3  Григорий Соколов               36           Москва

                           Информация
0      ФИО: Анна Иванова, Возраст: 26
1      ФИО: Борис Петров, Возраст: 31
2    ФИО: Виктор Смирнов, Возраст: 29
3  ФИО: Григорий Соколов, Возраст: 36

Исходный DataFrame (df) - не изменился:
                 ФИО  Возраст_в_годах Населенный пункт  \
0      Анна Иванова               26           Москва
1      Борис Петров               31        Петербург
2    Виктор Смирнов               29           Казань
3  Григорий Соколов               36           Москва

                           Информация
0      ФИО: Анна Иванова, Возраст: 26
1      ФИО: Борис Петров, Возраст: 31
2    ФИО: Виктор Смирнов, Возраст: 29
3  ФИО: Григорий Соколов, Возраст: 36

2. Сортировка по нескольким столбцам:

Сначала сортируем по 'Населенный пункт' (в алфавитном порядке), а внутри каждого населенного пункта – по 'Возраст_в_годах' (по возрастанию).

In [36]:
df_sorted_by_city_age = df.sort_values(by=['Населенный пункт', 'Возраст_в_годах']) # Сортируем по 'Населенный пункт', потом по 'Возраст_в_годах'

print("\nDataFrame, отсортированный по 'Населенный пункт' и 'Возраст_в_годах':\n", df_sorted_by_city_age)

DataFrame, отсортированный по 'Населенный пункт' и 'Возраст_в_годах':
                 ФИО  Возраст_в_годах Населенный пункт  \
2    Виктор Смирнов               29           Казань
0      Анна Иванова               26           Москва
3  Григорий Соколов               36           Москва
1      Борис Петров               31        Петербург

                           Информация
2    ФИО: Виктор Смирнов, Возраст: 29
0      ФИО: Анна Иванова, Возраст: 26
3  ФИО: Григорий Соколов, Возраст: 36
1      ФИО: Борис Петров, Возраст: 31

4. Сортировка по индексу (по возрастанию):

В нашем примере индекс - это просто порядковые номера строк (0, 1, 2, ...), поэтому сортировка по индексу в данном случае не изменит порядок строк. Но если бы у нас был индекс, например, с датами или какими-то идентификаторами, сортировка по индексу могла бы быть полезна.

In [37]:
df_sorted_by_index = df.sort_index() # Сортируем по индексу (по умолчанию axis=0, ascending=True)

print("\nDataFrame, отсортированный по индексу (по возрастанию):\n", df_sorted_by_index) # В данном случае порядок строк не изменится

DataFrame, отсортированный по индексу (по возрастанию):
                 ФИО  Возраст_в_годах Населенный пункт  \
0      Анна Иванова               26           Москва
1      Борис Петров               31        Петербург
2    Виктор Смирнов               29           Казань
3  Григорий Соколов               36           Москва

                           Информация
0      ФИО: Анна Иванова, Возраст: 26
1      ФИО: Борис Петров, Возраст: 31
2    ФИО: Виктор Смирнов, Возраст: 29
3  ФИО: Григорий Соколов, Возраст: 36

Практическое задание:

Используя DataFrame df:

Отсортируй DataFrame по столбцу 'ФИО' по убыванию.

Отсортируй DataFrame сначала по столбцу 'Населенный пункт' (по алфавиту), а затем внутри каждого города отсортируй по столбцу 'Возраст_в_годах' по убыванию.

Создай DataFrame df_shuffled путем случайного перемешивания строк исходного df (например, с помощью df.sample(frac=1).reset_index(drop=True) - это "продвинутый" способ, можешь просто скопировать, если интересно, разберем позже). Затем отсортируй df_shuffled по индексу (по возрастанию). Убедись, что после сортировки по индексу строки вернулись в "исходный" порядок индексов (0, 1, 2, ...), но значения строк остались перемешанными.

Выведи на экран все отсортированные DataFrame. Поэкспериментируй с разными параметрами sort_values() и sort_index().

Чего мы не прошли в Pandas, но что тоже важно:

Чтение и запись данных: Мы пока не рассматривали, как загружать данные из файлов (CSV, Excel и т.д.) в DataFrame и как сохранять DataFrame обратно в файлы. Это важный практический навык, и мы обязательно к нему вернемся.

Более сложные манипуляции: Pandas предлагает еще много возможностей для манипуляции данными, например:

Группировка и агрегирование данных (groupby)

Объединение нескольких DataFrame (merge, join)

Работа с пропущенными данными (dropna, fillna)

Изменение типа данных столбцов (astype)

И многое другое!